Change unit arguments from hard-coded lxd to SNAP_INSTANCE_NAME.
Creating your own personal snap of lxd with a different name fails during
installation because the daemon.activate and daemon.start scripts hard-code
the snap name to lxd:

```console
error: cannot perform the following tasks:
- Start snap "virtuous-sloth-lxd" (unset) services (systemctl command [start snap.virtuous-sloth-lxd.activate.service] failed with exit status 1: Job for snap.virtuous-sloth-lxd.activate.service failed because the control process exited with error code.
See "systemctl status snap.virtuous-sloth-lxd.activate.service" and "journalctl -xeu snap.virtuous-sloth-lxd.activate.service" for details.
```

I can do devmode without changing the snap name but would like to try
publishing virtuous-sloth-lxd in snapcraft.io for my own edification of the
whole process.

I chose SNAP_INSTANCE_NAME instead of SNAP_NAME even though lxd does not
support multiple instances because it seemed the right thing to do anyway.